version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
                CLIENT_PORT: ${CLIENT_PORT}
                DOCKER_BUILD: 'true'
        depends_on:
            server: 
                condition: service_started
        restart: always
        ports:
            - "443:443"
            - "${CLIENT_PORT}:80"
        environment:
            - CLIENT_PORT=${CLIENT_PORT}
            - SERVER_PORT=${SERVER_PORT}
        networks: 
            - awesome
        links:
            - server

    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
                SERVER_PORT: ${SERVER_PORT}
        depends_on:
            postgres:
                condition: service_healthy
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
            DOCKER_BUILD: 'true'
            SERVER_PORT: ${SERVER_PORT}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: prakticum-postgres
        networks: 
            - awesome

    postgres:
        container_name: prakticum-postgres
        image: postgres:14
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - prakticum-postgres:/var/lib/postgresql/data
        networks: 
            - awesome
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    prakticum-postgres:
        driver: local

networks:
    awesome:
        driver: bridge
