services:
    client:
        container_name: prakticum-client
        image: {{ env.CLIENT_IMAGE }}
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
                CLIENT_PORT: 3001
                DOCKER_BUILD: 'true'
        depends_on:
            server: 
                condition: service_started
        restart: always
        ports:
            - "443:443"
            - "3001:80"
        environment:
            - CLIENT_PORT=3001
            - SERVER_PORT=3000
        networks: 
            - awesome
        links:
            - server

    server:
        container_name: prakticum-server
        image: {{ env.SERVER_IMAGE }}
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
                SERVER_PORT: 3000
        depends_on:
            postgres:
                condition: service_healthy
        restart: always
        ports:
            - "3000:3000"
        environment:
            DOCKER_BUILD: 'true'
            SERVER_PORT: 3000
            POSTGRES_PORT: 5432
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST: prakticum-postgres
        networks: 
            - awesome

    postgres:
        container_name: prakticum-postgres
        image: postgres:14
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - prakticum-postgres:/var/lib/postgresql/data
        networks: 
            - awesome
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    prakticum-postgres:
        driver: local

networks:
    awesome:
        driver: bridge    
